export type StrategicLocation = {
  id: string;
  name: string;
  type: "headquarters" | "branch" | "marketing" | "service";
  typeLabel: string;
  country: "China" | "Singapore" | "United States" | "Japan" | "Germany" | "United Kingdom";
  countryLabel: string;
  province?: string;
  city?: string;
  longitude: number;
  latitude: number;
  establishment?: string;
};

export type RegionMetric = {
  name: string;
  value: number;
};

export const names = {
  headquarters: "总部",
  branch: "分公司",
  marketing: "营销分部",
  service: "服务中心",
  china: "中国",
  singapore: "新加坡",
  unitedStates: "美国",
  japan: "日本",
  germany: "德国",
  unitedKingdom: "英国",
  guangdong: "广东省",
  jiangsu: "江苏省",
  shanghai: "上海市",
  beijing: "北京市",
  shenzhen: "深圳市",
  guangzhou: "广州市",
  losAngeles: "洛杉矶",
  tokyo: "东京",
  berlin: "柏林",
  london: "伦敦",
} as const;

export const regionMetrics: RegionMetric[] = [
  { name: "China", value: 8 },
  { name: "United States of America", value: 4 },
  { name: "Japan", value: 2 },
  { name: "Germany", value: 2 },
  { name: "United Kingdom", value: 1 },
  { name: "Singapore", value: 1 },
];

export const strategicLocations: StrategicLocation[] = [
  {
    id: "hq-shenzhen",
    name: "汉理新能总部",
    type: "headquarters",
    typeLabel: names.headquarters,
    country: "China",
    countryLabel: names.china,
    province: names.guangdong,
    city: names.shenzhen,
    longitude: 114.0579,
    latitude: 22.5431,
    establishment: "2010",
  },
  {
    id: "branch-beijing",
    name: "北京分公司",
    type: "branch",
    typeLabel: names.branch,
    country: "China",
    countryLabel: names.china,
    province: names.beijing,
    city: names.beijing,
    longitude: 116.4074,
    latitude: 39.9042,
    establishment: "2015",
  },
  {
    id: "marketing-shanghai",
    name: "上海营销分部",
    type: "marketing",
    typeLabel: names.marketing,
    country: "China",
    countryLabel: names.china,
    province: names.shanghai,
    city: names.shanghai,
    longitude: 121.4737,
    latitude: 31.2304,
    establishment: "2016",
  },
  {
    id: "service-guangzhou",
    name: "广州服务中心",
    type: "service",
    typeLabel: names.service,
    country: "China",
    countryLabel: names.china,
    province: names.guangdong,
    city: names.guangzhou,
    longitude: 113.2644,
    latitude: 23.1291,
    establishment: "2018",
  },
  {
    id: "branch-nanjing",
    name: "南京分公司",
    type: "branch",
    typeLabel: names.branch,
    country: "China",
    countryLabel: names.china,
    province: names.jiangsu,
    city: "南京市",
    longitude: 118.7969,
    latitude: 32.0603,
    establishment: "2017",
  },
  {
    id: "branch-shanghai",
    name: "上海分公司",
    type: "branch",
    typeLabel: names.branch,
    country: "China",
    countryLabel: names.china,
    province: names.shanghai,
    city: names.shanghai,
    longitude: 121.5,
    latitude: 31.3,
    establishment: "2016",
  },
  {
    id: "regional-singapore",
    name: "新加坡区域总部",
    type: "branch",
    typeLabel: names.branch,
    country: "Singapore",
    countryLabel: names.singapore,
    city: names.singapore,
    longitude: 103.8198,
    latitude: 1.3521,
    establishment: "2019",
  },
  {
    id: "service-singapore",
    name: "新加坡服务中心",
    type: "service",
    typeLabel: names.service,
    country: "Singapore",
    countryLabel: names.singapore,
    city: names.singapore,
    longitude: 103.82,
    latitude: 1.36,
    establishment: "2020",
  },
  {
    id: "branch-losangeles",
    name: "洛杉矶分公司",
    type: "branch",
    typeLabel: names.branch,
    country: "United States",
    countryLabel: names.unitedStates,
    city: names.losAngeles,
    longitude: -118.2437,
    latitude: 34.0522,
    establishment: "2020",
  },
  {
    id: "marketing-losangeles",
    name: "洛杉矶营销分部",
    type: "marketing",
    typeLabel: names.marketing,
    country: "United States",
    countryLabel: names.unitedStates,
    city: names.losAngeles,
    longitude: -118.24,
    latitude: 34.06,
    establishment: "2021",
  },
  {
    id: "marketing-newyork",
    name: "纽约营销分部",
    type: "marketing",
    typeLabel: names.marketing,
    country: "United States",
    countryLabel: names.unitedStates,
    city: "纽约市",
    longitude: -74.0060,
    latitude: 40.7128,
    establishment: "2022",
  },
  {
    id: "service-chicago",
    name: "芝加哥服务中心",
    type: "service",
    typeLabel: names.service,
    country: "United States",
    countryLabel: names.unitedStates,
    city: "芝加哥",
    longitude: -87.6298,
    latitude: 41.8781,
    establishment: "2021",
  },
  {
    id: "branch-tokyo",
    name: "东京分公司",
    type: "branch",
    typeLabel: names.branch,
    country: "Japan",
    countryLabel: names.japan,
    city: names.tokyo,
    longitude: 139.6917,
    latitude: 35.6762,
    establishment: "2021",
  },
  {
    id: "service-tokyo",
    name: "东京服务中心",
    type: "service",
    typeLabel: names.service,
    country: "Japan",
    countryLabel: names.japan,
    city: names.tokyo,
    longitude: 139.69,
    latitude: 35.68,
    establishment: "2022",
  },
  {
    id: "branch-berlin",
    name: "柏林分公司",
    type: "branch",
    typeLabel: names.branch,
    country: "Germany",
    countryLabel: names.germany,
    city: names.berlin,
    longitude: 13.4050,
    latitude: 52.5200,
    establishment: "2022",
  },
  {
    id: "marketing-berlin",
    name: "柏林营销分部",
    type: "marketing",
    typeLabel: names.marketing,
    country: "Germany",
    countryLabel: names.germany,
    city: names.berlin,
    longitude: 13.41,
    latitude: 52.53,
    establishment: "2023",
  },
  {
    id: "service-london",
    name: "伦敦服务中心",
    type: "service",
    typeLabel: names.service,
    country: "United Kingdom",
    countryLabel: names.unitedKingdom,
    city: names.london,
    longitude: -0.1278,
    latitude: 51.5074,
    establishment: "2023",
  },
];
