import {
  PrismaClient,
  StrategicLocationStatus,
  StrategicLocationType,
} from "@prisma/client";

const prisma = new PrismaClient();

const items = [
  {
    code: "shenzhen-hq",
    nameZh: "汉理新能源总部",
    nameEn: "Hanli Energy Headquarters",
    type: StrategicLocationType.HEADQUARTERS,
    countryCode: "CN",
    countryNameZh: "中国",
    countryNameEn: "China",
    provinceNameZh: "广东省",
    provinceNameEn: "Guangdong",
    cityNameZh: "深圳市",
    cityNameEn: "Shenzhen",
    longitude: 114.0579,
    latitude: 22.5431,
    establishment: "2010",
    staff: 500,
    descriptionZh: "全球总部，负责研发、制造、销售和运营管理。",
    descriptionEn:
      "Global headquarters responsible for R&D, manufacturing, sales and operations management.",
    businessScopeZh: ["研发", "生产", "销售", "管理"],
    businessScopeEn: ["R&D", "Manufacturing", "Sales", "Management"],
    imageUrl: "/images/locations/shenzhen-hq.jpeg",
    sortOrder: 10,
  },
  {
    code: "guangzhou-service",
    nameZh: "广州服务中心",
    nameEn: "Guangzhou Service Center",
    type: StrategicLocationType.SERVICE,
    countryCode: "CN",
    countryNameZh: "中国",
    countryNameEn: "China",
    provinceNameZh: "广东省",
    provinceNameEn: "Guangdong",
    cityNameZh: "广州市",
    cityNameEn: "Guangzhou",
    longitude: 113.2644,
    latitude: 23.1291,
    establishment: "2018",
    staff: 95,
    descriptionZh: "粤港澳大湾区服务枢纽，提供技术支持和售后服务。",
    descriptionEn:
      "Service hub for the Greater Bay Area, providing technical support and after-sales service.",
    businessScopeZh: ["技术支持", "维修维护", "售后服务"],
    businessScopeEn: ["Technical Support", "Maintenance", "After-sales Service"],
    imageUrl: "/images/locations/guangzhou-service.jpeg",
    sortOrder: 20,
  },
  {
    code: "beijing-branch",
    nameZh: "北京分公司",
    nameEn: "Beijing Branch",
    type: StrategicLocationType.BRANCH,
    countryCode: "CN",
    countryNameZh: "中国",
    countryNameEn: "China",
    provinceNameZh: "北京市",
    provinceNameEn: "Beijing",
    cityNameZh: "北京市",
    cityNameEn: "Beijing",
    longitude: 116.4074,
    latitude: 39.9042,
    establishment: "2015",
    staff: 120,
    descriptionZh: "华北地区运营中心，负责北方市场开发和客户服务。",
    descriptionEn:
      "North China operations center for market development and customer service.",
    businessScopeZh: ["销售", "客户服务", "技术支持"],
    businessScopeEn: ["Sales", "Customer Service", "Technical Support"],
    imageUrl: "/images/locations/beijing-branch.jpeg",
    sortOrder: 30,
  },
  {
    code: "shanghai-marketing",
    nameZh: "上海营销分部",
    nameEn: "Shanghai Marketing Office",
    type: StrategicLocationType.MARKETING,
    countryCode: "CN",
    countryNameZh: "中国",
    countryNameEn: "China",
    provinceNameZh: "上海市",
    provinceNameEn: "Shanghai",
    cityNameZh: "上海市",
    cityNameEn: "Shanghai",
    longitude: 121.4737,
    latitude: 31.2304,
    establishment: "2016",
    staff: 85,
    descriptionZh: "华东地区营销总部，服务长三角市场。",
    descriptionEn:
      "East China marketing hub serving the Yangtze River Delta market.",
    businessScopeZh: ["市场营销", "品牌推广", "客户管理"],
    businessScopeEn: ["Marketing", "Brand Promotion", "Customer Management"],
    imageUrl: null,
    sortOrder: 40,
  },
  {
    code: "nanjing-branch",
    nameZh: "南京分公司",
    nameEn: "Nanjing Branch",
    type: StrategicLocationType.BRANCH,
    countryCode: "CN",
    countryNameZh: "中国",
    countryNameEn: "China",
    provinceNameZh: "江苏省",
    provinceNameEn: "Jiangsu",
    cityNameZh: "南京市",
    cityNameEn: "Nanjing",
    longitude: 118.7969,
    latitude: 32.0603,
    establishment: "2017",
    staff: 75,
    descriptionZh: "江苏区域总部，服务长江经济带中部地区。",
    descriptionEn:
      "Jiangsu regional office serving the central Yangtze River Economic Belt.",
    businessScopeZh: ["销售", "技术服务", "产品推广"],
    businessScopeEn: ["Sales", "Technical Service", "Product Promotion"],
    imageUrl: null,
    sortOrder: 50,
  },
  {
    code: "singapore-regional-hq",
    nameZh: "新加坡区域总部",
    nameEn: "Singapore Regional Headquarters",
    type: StrategicLocationType.BRANCH,
    countryCode: "SG",
    countryNameZh: "新加坡",
    countryNameEn: "Singapore",
    provinceNameZh: null,
    provinceNameEn: null,
    cityNameZh: "新加坡",
    cityNameEn: "Singapore",
    longitude: 103.8198,
    latitude: 1.3521,
    establishment: "2019",
    staff: 60,
    descriptionZh: "亚太地区运营与服务中心，辐射东南亚市场。",
    descriptionEn:
      "Asia-Pacific operations and service center covering Southeast Asian markets.",
    businessScopeZh: ["区域销售", "市场拓展", "客户支持"],
    businessScopeEn: ["Regional Sales", "Market Expansion", "Customer Support"],
    imageUrl: null,
    sortOrder: 60,
  },
  {
    code: "singapore-service",
    nameZh: "新加坡服务中心",
    nameEn: "Singapore Service Center",
    type: StrategicLocationType.SERVICE,
    countryCode: "SG",
    countryNameZh: "新加坡",
    countryNameEn: "Singapore",
    provinceNameZh: null,
    provinceNameEn: null,
    cityNameZh: "新加坡",
    cityNameEn: "Singapore",
    longitude: 103.82,
    latitude: 1.36,
    establishment: "2020",
    staff: 40,
    descriptionZh: "东南亚技术服务中心，提供本地化技术支持。",
    descriptionEn:
      "Southeast Asia technical service center providing localized support.",
    businessScopeZh: ["技术服务", "产品维护", "培训服务"],
    businessScopeEn: ["Technical Service", "Product Maintenance", "Training"],
    imageUrl: null,
    sortOrder: 70,
  },
  {
    code: "los-angeles-branch",
    nameZh: "洛杉矶分公司",
    nameEn: "Los Angeles Branch",
    type: StrategicLocationType.BRANCH,
    countryCode: "US",
    countryNameZh: "美国",
    countryNameEn: "United States",
    provinceNameZh: null,
    provinceNameEn: "California",
    cityNameZh: "洛杉矶",
    cityNameEn: "Los Angeles",
    longitude: -118.2437,
    latitude: 34.0522,
    establishment: "2020",
    staff: 110,
    descriptionZh: "北美西部运营中心，覆盖加州及周边地区。",
    descriptionEn:
      "West Coast operations center covering California and nearby regions.",
    businessScopeZh: ["销售", "产品展示", "客户服务"],
    businessScopeEn: ["Sales", "Product Showcase", "Customer Service"],
    imageUrl: "/images/locations/losangeles-branch.jpeg",
    sortOrder: 80,
  },
  {
    code: "tokyo-branch",
    nameZh: "东京分公司",
    nameEn: "Tokyo Branch",
    type: StrategicLocationType.BRANCH,
    countryCode: "JP",
    countryNameZh: "日本",
    countryNameEn: "Japan",
    provinceNameZh: null,
    provinceNameEn: "Tokyo",
    cityNameZh: "东京",
    cityNameEn: "Tokyo",
    longitude: 139.6917,
    latitude: 35.6762,
    establishment: "2021",
    staff: 130,
    descriptionZh: "日本运营总部，服务日本市场和技术合作。",
    descriptionEn:
      "Japan operations office supporting local market development and technical collaboration.",
    businessScopeZh: ["销售", "技术研发", "客户支持"],
    businessScopeEn: ["Sales", "Technical R&D", "Customer Support"],
    imageUrl: "/images/locations/tokyo-branch.jpeg",
    sortOrder: 90,
  },
  {
    code: "berlin-branch",
    nameZh: "柏林分公司",
    nameEn: "Berlin Branch",
    type: StrategicLocationType.BRANCH,
    countryCode: "DE",
    countryNameZh: "德国",
    countryNameEn: "Germany",
    provinceNameZh: null,
    provinceNameEn: "Berlin",
    cityNameZh: "柏林",
    cityNameEn: "Berlin",
    longitude: 13.405,
    latitude: 52.52,
    establishment: "2022",
    staff: 140,
    descriptionZh: "欧洲中心总部，连接欧洲主要市场。",
    descriptionEn: "European hub connecting key markets across Europe.",
    businessScopeZh: ["欧洲销售", "技术创新", "合规管理"],
    businessScopeEn: ["European Sales", "Technical Innovation", "Compliance Management"],
    imageUrl: "/images/locations/berlin-branch.jpeg",
    sortOrder: 100,
  },
];

async function main() {
  for (const item of items) {
    await prisma.strategicLocation.upsert({
      where: { code: item.code },
      update: {
        ...item,
        status: StrategicLocationStatus.PUBLISHED,
        enabled: true,
      },
      create: {
        ...item,
        status: StrategicLocationStatus.PUBLISHED,
        enabled: true,
      },
    });
  }

  const total = await prisma.strategicLocation.count({
    where: { deletedAt: null },
  });
  const published = await prisma.strategicLocation.count({
    where: {
      deletedAt: null,
      enabled: true,
      status: StrategicLocationStatus.PUBLISHED,
    },
  });

  console.log(
    `Seeded ${items.length} strategic locations. Total active rows: ${total}. Published enabled rows: ${published}.`,
  );
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
